#!/data/data/com.termux/files/usr/bin/sh

## System
echo '>> Updating packages'
pkg update

## Rust
if which rustup > /dev/null 2>&1
then
	echo '>> Updating rust'
	rustup update
fi

## Python
python=$(which python python3 python2 2> /dev/null | head -1)
if [ -n "$python" ]
then
	if ! $python -m pip --version > /dev/null 2>&1
	then
		echo '>> Installing pip'
		$python -m ensurepip --user --default-pip
	fi

	echo '>> Updating pip'
	$python -m pip install --user --upgrade pip

	echo '>> Updating Python packages'
	$python -m pip list --format freeze --not-required \
	| sed 's/==.*//' | grep -Fvx pip | sort -u \
	| xargs -r $python -m pip install --user --upgrade
fi

## Other
if [ -d "$0.d" ]
then
	for f in "$0.d"/*.sh
	do
		[ -r "$f" -a -x "$f" ] && . "$f"
	done
fi
